-- Seed KOMAL products from Komal_Price_List_01-06-2026.xlsx
-- Rows: 211
-- Product name, size, rate and quantity type come from the workbook.
-- The workbook Packing column is intentionally ignored.

insert into public.brands (name)
values ('KOMAL')
on conflict (name) do nothing;

update public.products
set is_active = false
where brand_id = (select id from public.brands where name = 'KOMAL');

with brand_row as (
  select id from public.brands where name = 'KOMAL'
), seed(item_name, size, rate, qty_type) as (
  values
    ('AKHAND GAS TROLLEY', 'STANDARD', 250.00, 'Pcs'),
    ('BABY IDLY STAND', '5 X 3', 210.00, 'Pcs'),
    ('BABY IDLY STAND', '5 X 4', 250.00, 'Pcs'),
    ('BABY IDLY STAND', '5 X 5', 300.00, 'Pcs'),
    ('BABY IDLY STAND', '5 X 6', 340.00, 'Pcs'),
    ('BELAN SUPER DELUXE (JOINTLESS)', 'STANDARD', 175.00, 'Pcs'),
    ('BIG IDLY COOKER WITH DHOKLA', '4 PLATES', 1400.00, 'Pcs'),
    ('BIG IDLY COOKER WITH IDLY STAND', '4X5', 1190.00, 'Pcs'),
    ('BIG IDLY COOKER WITH IDLY STAND', '4X6', 1235.00, 'Pcs'),
    ('BIG IDLY COOKER WITH MULTY', '3 PLATES', 1570.00, 'Pcs'),
    ('BIG IDLY COOKER WITH MULTY', '4 PLATES', 1745.00, 'Pcs'),
    ('BIG THAAT IDLY COOKER WITH MULTY', '5 PLATES', 0.00, 'Pcs'),
    ('BIG THAAT IDLY COOKER WITH MULTY', '6 PLATES', 0.00, 'Pcs'),
    ('BIG THAAT IDLY COOKER WITH PLATES THAAT IDLY STAND', '6 PLATES', 0.00, 'Pcs'),
    ('BIG THAAT IDLY COOKER WITH THAAT IDLY STAND', '5 PLATES', 0.00, 'Pcs'),
    ('CAPPUCCINO DOUBLE WALL MUG BIG', '2 PCS.SET', 305.00, 'Box'),
    ('CAPPUCCINO DOUBLE WALL MUG SMALL', '2 PCS.SET', 270.00, 'Box'),
    ('COCONUT DELUXE (VACUUM BASE )', 'STANDARD', 230.00, 'Pcs'),
    ('COCONUT PATIYA (S.S. BASE )', 'STANDARD', 230.00, 'Pcs'),
    ('COFFEE POT (2 CUPS)', '500 ML', 305.00, 'Pcs'),
    ('COFFEE POT (4 CUPS)', '750 ML', 335.00, 'Pcs'),
    ('COFFEE POT (6 CUPS)', '960 ML', 375.00, 'Pcs'),
    ('CUP & SAUCER SET DOUBLE WALL', '4 PCS. SET', 525.00, 'Box'),
    ('DELUXE GAS TROLLEY', 'STANDARD', 235.00, 'Pcs'),
    ('DELUXE PATLA', 'STANDARD', 425.00, 'Pcs'),
    ('DHOKLA ( HAWKINS TYPE )', 'FOUR PLATES', 500.00, 'Pcs'),
    ('DHOKLA ( HAWKINS TYPE )', 'THREE PLATES', 445.00, 'Pcs'),
    ('DHOKLA ( PRESTIGE TYPE )', 'FOUR PLATES', 570.00, 'Pcs'),
    ('DHOKLA ( PRESTIGE TYPE )', 'THREE PLATES', 510.00, 'Pcs'),
    ('GARLIC CRUSHER', 'STANDARD', 200.00, 'Pcs'),
    ('IDLY COOKER (PRESSING)', 'BIG', 840.00, 'Pcs'),
    ('IDLY COOKER (PRESSING)', 'SMALL', 790.00, 'Pcs'),
    ('IDLY COOKER WITH HAW. DHOKLA', '3 PLATES', 885.00, 'Pcs'),
    ('IDLY COOKER WITH HAW. IDLY STAND', '3X4', 760.00, 'Pcs'),
    ('IDLY STAND ( HAWKINS TYPE )', '3 X 3', 220.00, 'Pcs'),
    ('IDLY STAND ( HAWKINS TYPE )', '3 X 4', 260.00, 'Pcs'),
    ('IDLY STAND ( HAWKINS TYPE )', '3 X 5', 325.00, 'Pcs'),
    ('IDLY STAND ( HAWKINS TYPE )', '3 X 6', 360.00, 'Pcs'),
    ('IDLY STAND ( PRESTIGE TYPE )', '4 X 3', 235.00, 'Pcs'),
    ('IDLY STAND ( PRESTIGE TYPE )', '4 X 4', 290.00, 'Pcs'),
    ('IDLY STAND ( PRESTIGE TYPE )', '4 X 5', 360.00, 'Pcs'),
    ('IDLY STAND ( PRESTIGE TYPE )', '4 X 6', 405.00, 'Pcs'),
    ('JANTA PATLA', 'STANDARD', 375.00, 'Pcs'),
    ('JEWELLERY BOX ( 14”)', 'JUMBO', 850.00, 'Pcs'),
    ('JEWELLERY BOX ( 8”)', 'SMALL', 460.00, 'Pcs'),
    ('JEWELLERY BOX ( 8”) (WITHOUT VELVET)', 'SMALL', 385.00, 'Pcs'),
    ('JEWELLERY BOX (10”)', 'MEDIUM', 525.00, 'Pcs'),
    ('JEWELLERY BOX (10”) (WITHOUT VELVET)', 'MEDIUM', 450.00, 'Pcs'),
    ('JEWELLERY BOX (12”)', 'BIG', 590.00, 'Pcs'),
    ('JEWELLERY BOX (12”) (WITHOUT VELVET)', 'BIG', 515.00, 'Pcs'),
    ('LIME SQUEEZER', 'STANDARD', 155.00, 'Pcs'),
    ('MILK & SUGAR POT WITH LID (170 ML.)', '6 OZ', 305.00, 'Pcs'),
    ('MILK & SUGAR POT WITH LID (300 ML.)', '10 OZ', 330.00, 'Pcs'),
    ('MINI IDLY STAND ( HAWKINS TYPE )', '15 X 3', 230.00, 'Pcs'),
    ('MINI IDLY STAND ( HAWKINS TYPE )', '15 X 4', 270.00, 'Pcs'),
    ('MINI IDLY STAND ( HAWKINS TYPE )', '15 X 5', 330.00, 'Pcs'),
    ('MINI IDLY STAND ( HAWKINS TYPE )', '15 X 6', 365.00, 'Pcs'),
    ('MINI IDLY STAND ( PRESTIGE TYPE )', '18 X 3', 245.00, 'Pcs'),
    ('MINI IDLY STAND ( PRESTIGE TYPE )', '18 X 4', 300.00, 'Pcs'),
    ('MINI IDLY STAND ( PRESTIGE TYPE )', '18 X 5', 365.00, 'Pcs'),
    ('MINI IDLY STAND ( PRESTIGE TYPE )', '18 X 6', 410.00, 'Pcs'),
    ('MULTY KADAI SET (WITH )', 'SIX PLATES', 1875.00, 'Pcs'),
    ('MULTY SET - 3', 'THREE PLATES', 740.00, 'Pcs'),
    ('MULTY SET - 3 ( WITHOUT CHINA ) TWO IN ONE - 3', 'STANDARD', 615.00, 'Pcs'),
    ('MULTY SET - 4', 'FOUR PLATES', 915.00, 'Pcs'),
    ('MULTY SET - 4 ( WITHOUT CHINA ) TWO IN ONE - 4', 'STANDARD', 735.00, 'Pcs'),
    ('NON STICK APPACHETTY', 'STANDARD', 575.00, 'Pcs'),
    ('NON STICK APPAM PATRA (12 CAVITIES)', 'STANDARD', 575.00, 'Pcs'),
    ('NON STICK APPAM PATRA WITH GLASS LID-12(HEAVY)', 'STANDARD', 850.00, 'Pcs'),
    ('NON STICK FLAT DOSA TAWA DIA', '350MM', 925.00, 'Pcs'),
    ('NON STICK FLAT DOSA TAWA DIA 350MM(INDUCTION)', 'STANDARD', 1025.00, 'Pcs'),
    ('NON STICK GRILL PAN (', '24CM', 650.00, 'Pcs'),
    ('NON STICK JUMBO GRILL TOASTER', 'STANDARD', 650.00, 'Pcs'),
    ('NON STICK JUMBO GRILL TOASTER 2 CUT', 'STANDARD', 650.00, 'Pcs'),
    ('NON STICK JUMBO GRILL TOASTER 4 CUT', 'STANDARD', 650.00, 'Pcs'),
    ('NON STICK TOASTER', 'STANDARD', 285.00, 'Pcs'),
    ('NON STICK TOASTER GRILL', 'STANDARD', 325.00, 'Pcs'),
    ('NON STICK UTTAPAM (4 CAVITIES )', 'STANDARD', 475.00, 'Pcs'),
    ('NON STICK WAFFLE MAKER', 'STANDARD', 650.00, 'Pcs'),
    ('OIL DISPENSER', '250 ML', 235.00, 'Pcs'),
    ('OIL DISPENSER', '350 ML', 255.00, 'Pcs'),
    ('OIL DISPENSER', '500 ML', 280.00, 'Pcs'),
    ('OIL DISPENSER', '750 ML', 340.00, 'Pcs'),
    ('OIL DISPENSER', '1000 ML', 380.00, 'Pcs'),
    ('OIL DISPENSER - 1000ML. (COPPER FINISH.)', 'STANDARD', 515.00, 'Pcs'),
    ('OIL DISPENSER - 350ML. (COPPER FINISH).', 'STANDARD', 385.00, 'Pcs'),
    ('OIL DISPENSER - 500ML. (COPPER FINISH).', 'STANDARD', 420.00, 'Pcs'),
    ('OIL DISPENSER - 750ML. (COPPER FINISH).', 'STANDARD', 485.00, 'Pcs'),
    ('OIL N JUICE', '1200 ML', 400.00, 'Pcs'),
    ('OIL N. JUICE', '1000 ML', 375.00, 'Pcs'),
    ('OIL POT \ KAWLA', '450 ML', 180.00, 'Pcs'),
    ('OIL POT \ KAWLA', '550 ML', 205.00, 'Pcs'),
    ('OIL POT \ KAWLA', '750 ML', 235.00, 'Pcs'),
    ('OIL POT \ KAWLA', '1000 ML', 270.00, 'Pcs'),
    ('OIL POT \ KAWLA', '1200 ML', 300.00, 'Pcs'),
    ('OIL POT SUPER DELUXE ( INDICA )', 'NO. 1', 195.00, 'Pcs'),
    ('OIL POT SUPER DELUXE ( INDICA )', 'NO. 2', 220.00, 'Pcs'),
    ('PATLA', 'JUMBO', 525.00, 'Pcs'),
    ('PIZZA CUTTER', 'STANDARD', 200.00, 'Pcs'),
    ('POLPAT', 'STANDARD', 220.00, 'Pcs'),
    ('POLPAT JOINT LESS', 'STANDARD', 250.00, 'Pcs'),
    ('ROUND STOOL', 'NO. 6', 415.00, 'Pcs'),
    ('ROUND STOOL', 'NO. 8', 465.00, 'Pcs'),
    ('ROUND STOOL', 'NO. 11', 525.00, 'Pcs'),
    ('ROUND STOOL', 'NO. 15', 650.00, 'Pcs'),
    ('ROUND STOOL', 'NO. 18', 710.00, 'Pcs'),
    ('S.S BABY PETTI', 'NO. 01', 145.00, 'Pcs'),
    ('S.S BABY PETTI', 'NO. 02', 175.00, 'Pcs'),
    ('S.S BABY PETTI', 'NO. 03', 200.00, 'Pcs'),
    ('S.S MASALA PETTI JUMBO WITH NINE SQUARE WATI', 'NO. 9', 2025.00, 'Pcs'),
    ('S.S MASALA PETTI JUMBO WITH SIX SQUARE WATI', 'NO. 6', 1450.00, 'Pcs'),
    ('S.S MASALA PETTI MEDIUM WITH NINE SQUARE WATI', 'NO. 9', 1550.00, 'Pcs'),
    ('S.S MASALA PETTI MEDIUM WITH TWELVE SQUARE WATI', 'NO. 12', 2050.00, 'Pcs'),
    ('S.S MASALA PETTI NO.3 SIX WATI', 'STANDARD', 625.00, 'Pcs'),
    ('S.S MASALA PETTI NO.4 SIX WATI', 'STANDARD', 725.00, 'Pcs'),
    ('S.S MASALA PETTI NO.NINE WATI (MINI)', 'STANDARD', 825.00, 'Pcs'),
    ('S.S OIL DROPPER', '350ML', 315.00, 'Pcs'),
    ('S.S OIL DROPPER', '500ML', 375.00, 'Pcs'),
    ('S.S OIL DROPPER', '750ML', 420.00, 'Pcs'),
    ('S.S OIL DROPPER', '1000ML', 455.00, 'Pcs'),
    ('S.S ROUND MASALA DABBA 11 WITH S.S PLATE (WITHOUT SEE THROUGH)', 'STANDARD', 590.00, 'Pcs'),
    ('S.S ROUND MASALA DABBA 12 WITH S.S PLATE (WITHOUT SEE THROUGH)', 'STANDARD', 665.00, 'Pcs'),
    ('S.S ROUND SEE THROUGH MASALA DABBA 11', 'STANDARD', 590.00, 'Pcs'),
    ('S.S ROUND SEE THROUGH MASALA DABBA 11 (WITH PLATE ACRELIC OR S.S PLATE)', 'STANDARD', 690.00, 'Pcs'),
    ('S.S ROUND SEE THROUGH MASALA DABBA 12', 'STANDARD', 665.00, 'Pcs'),
    ('S.S ROUND SEE THROUGH MASALA DABBA 12 (WITH PLATE ACRELIC OR S.S PLATE)', 'STANDARD', 750.00, 'Pcs'),
    ('S.S ROUND SEE THROUGH MASALA DABBA 13', 'STANDARD', 735.00, 'Pcs'),
    ('S.S ROUND SEE THROUGH MASALA DABBA 13 (WITHOUT SEE THROUGH)', 'STANDARD', 685.00, 'Pcs'),
    ('S.S TRI PLY KADAI WITH S.S LID', '20CM', 1350.00, 'Pcs'),
    ('S.S TRI PLY KADAI WITH S.S LID', '22CM', 1475.00, 'Pcs'),
    ('S.S TRI PLY KADAI WITH S.S LID', '24CM', 1625.00, 'Pcs'),
    ('S.S TRI PLY KADAI WITH S.S LID', '26CM', 1775.00, 'Pcs'),
    ('S.S TRI PLY KADAI WITH S.S LID', '28CM', 1825.00, 'Pcs'),
    ('S.S TRI PLY KADAI WITH S.S LID', '30CM', 2100.00, 'Pcs'),
    ('S.S. BABY FEEDING BOTTLE', '150ML', 285.00, 'Pcs'),
    ('S.S. BABY FEEDING BOTTLE', '250ML', 335.00, 'Pcs'),
    ('S.S. FALAFEL MAKER NO.2', '35 MM', 0.00, 'Pcs'),
    ('S.S. FALAFEL MAKER NO.3', '40 MM', 0.00, 'Pcs'),
    ('S.S. FALAFEL MAKER NO.4', '45 MM', 0.00, 'Pcs'),
    ('S.S. FALAFEL MAKER NO.5', '60 MM', 0.00, 'Pcs'),
    ('S.S. FALAFEL MAKER NO.6', '65MM', 0.00, 'Pcs'),
    ('S.S. GREEN COCONUT OPENER', 'STANDARD', 185.00, 'Pcs'),
    ('S.S. KITCHEN EXPRESS', 'STANDARD', 365.00, 'Pcs'),
    ('S.S. MASALA PETTI JUMBO WITH TWELVE SQUARE WATI', 'NO. 12', 2550.00, 'Pcs'),
    ('S.S. MEDUWADAMAKER BOWLS', 'STANDARD', 225.00, 'Pcs'),
    ('S.S. POOJA PETTI', 'NO. 1', 195.00, 'Pcs'),
    ('S.S. POOJA PETTI', 'NO. 2', 220.00, 'Pcs'),
    ('S.S. POOJA PETTI', 'NO. 3', 275.00, 'Pcs'),
    ('S.S. POOJA PETTI NO.1 (WITH LOCK & KEY)', 'STANDARD', 250.00, 'Pcs'),
    ('S.S. POOJA PETTI NO.2 (WITH LOCK & KEY)', 'STANDARD', 280.00, 'Pcs'),
    ('S.S. POOJA PETTI NO.3 (WITH LOCK & KEY)', 'STANDARD', 330.00, 'Pcs'),
    ('S.S. POOJA PETTI NO.4 (WITH LOCK & KEY)', 'STANDARD', 390.00, 'Pcs'),
    ('S.S. SMASHER S. S. HANDLE ( DIA. 4 INCH )', 'STANDARD', 225.00, 'Pcs'),
    ('S.S.BANGLE AND JEWELLERY BOX', 'NO. 3', 900.00, 'Pcs'),
    ('S.S.BANGLE AND JEWELLERY BOX', 'NO. 4', 1000.00, 'Pcs'),
    ('S.S.FRUIT HANDY JUICER', 'STANDARD', 235.00, 'Pcs'),
    ('S.S.MULTIPURPOSE STORAGE CANISTER', '500ML', 235.00, 'Pcs'),
    ('S.S.MULTIPURPOSE STORAGE CANISTER', '750ML', 255.00, 'Pcs'),
    ('S.S.MULTIPURPOSE STORAGE CANISTER', '1000ML', 275.00, 'Pcs'),
    ('S.S.POOJA PETTI', 'NO. 4', 325.00, 'Pcs'),
    ('S.S.PURANMAKER BOWLS (1 JALI)', 'STANDARD', 300.00, 'Pcs'),
    ('S.S.PURANMAKER BOWLS (3 JALIES)', 'STANDARD', 460.00, 'Pcs'),
    ('S.S.PURANMAKER BOWLS (5 JALIES)', 'STANDARD', 490.00, 'Pcs'),
    ('S.S.SMASHER PLASTIC HANDLE (DIA. 4 INCH )', 'STANDARD', 130.00, 'Pcs'),
    ('S.S.SMASHER WOODEN HANDLE (DIA. 4 INCH )', 'STANDARD', 150.00, 'Pcs'),
    ('SCHOOL BAG', 'NO. 5', 450.00, 'Pcs'),
    ('SCHOOL BAG', 'NO. 6', 505.00, 'Pcs'),
    ('SCHOOL BAG', 'NO. 7', 570.00, 'Pcs'),
    ('SCHOOL BAG', 'NO. 8', 685.00, 'Pcs'),
    ('SLIM DOUBLE WALL TALL MUG', '2 PCS.SET', 330.00, 'Box'),
    ('SMALL IDLY COOKER WITH DHOKLA', '3 PLATES', 1290.00, 'Pcs'),
    ('SMALL IDLY COOKER WITH IDLY STAND', '4X3', 1015.00, 'Pcs'),
    ('SMALL IDLY COOKER WITH IDLY STAND', '4X4', 1070.00, 'Pcs'),
    ('SMALL IDLY COOKER WITH MULTY', '3 PLATES', 1520.00, 'Pcs'),
    ('SMALL THAAT IDLY COOKER WITH MULTY', '3 PLATES', 0.00, 'Pcs'),
    ('SMALL THAAT IDLY COOKER WITH MULTY', '4 PLATES', 0.00, 'Pcs'),
    ('SMALL THAAT IDLY COOKER WITH THAAT IDLY STAND', '3 PLATES', 0.00, 'Pcs'),
    ('SMALL THAAT IDLY COOKER WITH THAAT IDLY STAND', '4 PLATES', 0.00, 'Pcs'),
    ('SOBER DOUBLE WALL MUG BIG', '2 PCS.SET', 305.00, 'Box'),
    ('SOBER DOUBLE WALL MUG SMALL', '2 PCS.SET', 270.00, 'Box'),
    ('STAINLESS STEEL TEA CUP DOUBLE WALL', '6 PCS. SET', 525.00, 'Box'),
    ('SUPDA', 'BIG', 360.00, 'Pcs'),
    ('SUPDA', 'SMALL', 300.00, 'Pcs'),
    ('TEA POT (2 CUPS)', '480 ML', 250.00, 'Pcs'),
    ('TEA POT (4 CUPS)', '720 ML', 310.00, 'Pcs'),
    ('TEA POT (6 CUPS)', '1080 ML', 385.00, 'Pcs'),
    ('THAAT IDLY STAND', '3 PLATES', 440.00, 'Pcs'),
    ('THAAT IDLY STAND', '4 PLATES', 470.00, 'Pcs'),
    ('THAAT IDLY STAND', '5 PLATES', 500.00, 'Pcs'),
    ('THAAT IDLY STAND', '6 PLATES', 535.00, 'Pcs'),
    ('THAAT IDLY STEAMER BIG', 'STANDARD', 0.00, 'Pcs'),
    ('THAAT IDLY STEAMER SMALL', 'STANDARD', 0.00, 'Pcs'),
    ('THAAT MULTY SET - 3', 'THREE PLATES', 0.00, 'Pcs'),
    ('THAAT MULTY SET - 4', 'FOUR PLATES', 0.00, 'Pcs'),
    ('THAAT MULTY SET - 5', 'FIVE PLATES', 0.00, 'Pcs'),
    ('THAAT MULTY SET - 6', 'SIX PLATES', 0.00, 'Pcs'),
    ('TRI-PLY MULTY KADAI SET (WITH )', 'SIX PLATES', 2750.00, 'Pcs'),
    ('WHITE CAP OIL CAN SUPER DELUXE', '350 ML', 235.00, 'Pcs'),
    ('WHITE CAP OIL CAN SUPER DELUXE', '500 ML', 260.00, 'Pcs'),
    ('WHITE CAP OIL CAN SUPER DELUXE', '750 ML', 290.00, 'Pcs'),
    ('WHITE CAP OIL CAN SUPER DELUXE', '1000 ML', 350.00, 'Pcs'),
    ('WHITE CAP OIL CAN SUPER DELUXE', '1200 ML', 370.00, 'Pcs'),
    ('WIRE DHOKLA', '3 PLATES', 445.00, 'Pcs'),
    ('WIRE DHOKLA', '4 PLATES', 530.00, 'Pcs'),
    ('WOODEN HANDICRAFT JEWELLERY BOX BIG', 'STANDARD', 350.00, 'Pcs'),
    ('WOODEN HANDICRAFT JEWELLERY BOX MEDIUM', 'STANDARD', 300.00, 'Pcs'),
    ('WOODEN HANDICRAFT JEWELLERY BOX MINI', 'STANDARD', 175.00, 'Pcs'),
    ('WOODEN HANDICRAFT JEWELLERY BOX SMALL', 'STANDARD', 250.00, 'Pcs'),
    ('WRITING PAD', 'BIG', 255.00, 'Pcs'),
    ('WRITING PAD', 'MEDIUM', 220.00, 'Pcs'),
    ('WRITING PAD', 'SMALL', 190.00, 'Pcs')
), updated as (
  update public.products p
  set rate = seed.rate,
      is_active = true
  from seed, brand_row
  where p.brand_id = brand_row.id
    and upper(trim(p.item_name)) = upper(trim(seed.item_name))
    and regexp_replace(upper(trim(p.size)), '\s+', '', 'g') = regexp_replace(upper(trim(seed.size)), '\s+', '', 'g')
    and upper(trim(p.qty_type)) = upper(trim(seed.qty_type))
  returning p.id
)
insert into public.products (brand_id, item_name, size, rate, qty_type, is_active)
select brand_row.id, seed.item_name, seed.size, seed.rate, seed.qty_type, true
from seed
cross join brand_row
where not exists (
  select 1
  from public.products p
  where p.brand_id = brand_row.id
    and upper(trim(p.item_name)) = upper(trim(seed.item_name))
    and regexp_replace(upper(trim(p.size)), '\s+', '', 'g') = regexp_replace(upper(trim(seed.size)), '\s+', '', 'g')
    and upper(trim(p.qty_type)) = upper(trim(seed.qty_type))
);

select p.item_name, p.size, p.rate, p.qty_type
from public.products p
join public.brands b on b.id = p.brand_id
where upper(trim(b.name)) = 'KOMAL'
order by p.item_name, p.size;
